title: camera2d
description: A tiny helper library for working with the web audio API written in TypeScript.
base: "/camera2d/"
themeConfig:
  sidebarDepth: 0
  nav:
  - link: "/guide/"
    text: Guide
  - link: "/api/"
    text: API
  - link: "/camera2d/example/"
    text: Demo
    target: _blank
  - link: https://github.com/lusito/camera2d
    text: Github
  - link: https://www.npmjs.com/package/camera2d
    text: NPM
  sidebar:
    "/guide/":
    - title: Guide
      children:
      - ''
      - basic-camera
      - screen-camera
      - following-camera
      - influenced-camera
      - influenced-camera-target
      - influenced-camera-cue
  displayAllHeaders: true
plugins:
- fulltext-search
- typedoc
