title: PixlCam
description: A tiny helper library for working with the web audio API written in TypeScript.
base: "/pixlcam/"
themeConfig:
  sidebarDepth: 0
  nav:
  - link: "/guide/"
    text: Guide
  - link: "/api/"
    text: API
  - link: "/pixlcam/example/"
    text: Demo
    target: _blank
  - link: https://github.com/lusito/pixlcam
    text: Github
  - link: https://www.npmjs.com/package/pixlcam
    text: NPM
  sidebar:
    "/guide/":
    - title: Guide
      children:
      - ''
      - basic-camera
      - screen-camera
      - following-camera
      - influenced-camera
  displayAllHeaders: true
plugins:
- fulltext-search
- typedoc
